### ISSUE TITLE
admin: Return grpc error code in response to UpdateLogStream rpc.

### ISSUE THREAD

**Issue by hungryjang** [kakao/varlog#310]
UpdateLogStream RPC in the admin server returns vague error codes in some cases. Thus, the clients that call this RPC can have trouble handling errors.
To clarify and correctly handle the causes of errors, we need to define an explicit error code for every response from UpdateLogStream rather than depending on the `verrors` package.

**Comment by ijsong** [comment]
Edited description of this issue.
